before/config/routes.rb
ResqueDemo::Application.routes.draw do
  resources :episodes
  root 'episodes#index'

end

before/app/models/episode.rb
class Episode < ActiveRecord::Base
  def save_video_duration
    sleep 10
    result = `avconv -i #{self.asset_url} 2>&1`
    if result =~ /Duration: ([\d][\d]:[\d][\d]:[\d][\d].[\d]+)/
      self.update_attributes(duration: $1.to_s)
    end
  end
end

before/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

before/app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  def new
    @episode = Episode.new
  end

  def show
    @episode = Episode.find(params[:id])
  end

  def index
  end

  def create
    @episode = Episode.new(episode_params)
    if @episode.save
      @episode.save_video_duration
      redirect_to @episode
    else
      render :new
    end
  end

  private
   def episode_params
     params.require(:episode).permit(:asset_url)
   end
end

before/app/helpers/application_helper.rb
module ApplicationHelper
end

before/app/views/episodes/index.html.erb
<div class="page-indicator">
  episodes#index
</div>
<div class="new-episode-btn">
  <%= link_to "New Episode", new_episode_path, class: "button primary" %>
</div>

before/app/views/episodes/new.html.erb
<div class="single-form-container">
  <%= form_for @episode do |f| %>
    <div class="boxed-group">
      <h3>Create New Episode</h3>
      <div class="boxed-group-inner">
        <dl class="form">
          <dt><%= f.label :asset_url %></dt>
          <dd><%= f.text_field :asset_url %></dd>
        </dl>
        <p><%= f.submit "Save", :class => "button primary" %></p>
      </div>
    </div>
  <% end %>
</div>

before/app/views/episodes/show.html.erb
<div class="page-indicator">
  episodes#show
</div>
<div class="fake-screen">
  <div class="asset_url">
    <%= @episode.asset_url %>
  </div>
  <div class="duration">
    duration:
    <%= @episode.duration %>
  </div>
</div>

before/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ResqueDemo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>